Show Databases;
create database pdb3;
use pdb3;
create table students(
sid integer,
sname char(30),
age integer,
course char(30));	

show tables;
USE Pdb3;
show tables;
desc students;
insert into students values (1,'Amit',25,'MYSQL');
select * from students;
insert into students values (2,'suresh',23,'DA');
insert into students values (3,'nisha',21,'SQL');
insert into students values (4,'joy',24,'vb');

select * from students;

select 5 + null as result;
select 5 = null as result;
show tables;
create table students(sid integer, sname char(30));
create table patients(pid integer, pname varchar(255),dob date,toa datetime);
insert into patients values(21,'tejas','2024-02-23','2024-02-23 09:30:00');
select * from patients;
show tables;
select * from patients;
insert into students values(5,'john',asd,null,50);
show tables;
select *from students;
insert into students values (4,'jon',null,0,25);
select * from students;
update students set sname='Natasha' where stdid=1;
set sql_safe_updates = 0;
select * from students;
update students set marks = null where marks=0;
select * from students;
update students set course = 'Dance', marks = 80 where stdid=4;
select * from students;
delete from students where stdid = 2;
select * from students;
delete from students where marks is null;
select * from students;
delete from students where age is null;
select * from students;	
delete from students;
select * from students;
insert into students values(5,'john','asd',5,50);
insert into students values(5,'disha','as',3,20);
insert into students values(5,'esha','sd',2,10);
select * from students;
truncate students;
select * from students;
use pdb3;
Create database tejas;
use tejas;
create table students (Sid integer,sname varchar(30),marks integer, division varchar(30));
insert into students values (1,'tejas',85,'a');
insert into students values (2,'rucha',75,'b');
insert into students values (3,'ojas',95,'c');
insert into students values (4,'mahi',60,'d');
insert into students values (5,'kabeer',90,'e');
desc students;
select * from students;
select * from students rename column name 'division' equal to 'Div';
rename table students to tej;
alter table tej add column age integer default 0;
select * from tej;
alter table tej change column name marks to grade;
alter table tej drop column age;
select * from tej;
alter table tej change column Sid studentid integer;
select * from tej;
desc tej;
alter table tej modify column sname var(20);
alter table tej rename to students;
desc tables;
show tables;
SELECT * from students;
insert into students value(5,'peter',78,'e');
alter table students add column age integer default 0;
alter table students change column age sage integer;
alter table students drop column sage;
alter table students rename to student;
insert into student values (6,'pete',68);
alter table student rename to students;
SELECT * from students;
set sname = 'natasha' where stusentid=1;

set sname='natasha' where studentid=1;
select * from students;
update student set sname='nishi' where studentid=2;
desc students;
set sname='nishi'
where studentid=1;
update student set sname='nishi' where studentid=2;
use tejas;
update students set sname='nishi' where studentid=2;
select * from students;
update students set marks=0 where sname='mahi';
select * from students;
update students set marks =45,division='a' where studentid=5;
select * from students;
use tejas;
delete from students where studentid=2;
delete from students where division = 'a';
truncate from students;
delete from students;
truncate students;
select * from students;
use pdb3;
select * from movies;
select * from movies inner join members on movieid = id;
select * from movies join members on movieid = id;
select * from movies left join members on movieid - id;
select * from movies right join members on movieid = id;
select * from books;
select * from authors;
select title,name from authors inner join books on books.authorid = authors.authorid;
select * from meals cross join drinks;
select mealname,drinkname,meals.rate + drinks.rate as totalrate from meals cross join drinks;
select m.mealname,d.drinkname,m.rate + d.rate as totalrate from meals as m cross join drinks as d;
select emp_id,first_name,last_name,mgr_id from myemp limit 20;
select emp.emp_id,emp.first_name,emp.last_name,mgr.first_name as mgr_firstname,mgr.last_name as mgr_lastname from myemp as emp join myemp as mgr on emp.mgr_id = mgr.emp_id;
USE pdb3;
create view myview as select emp_id,first_name,last_name,salary from myemp;
select * from myview;
select mv.title,mm.first_name,mm.last_name from movies as mv left join members as mm on mv.id=mm.movieid;
select mv.title,ifnull(mm.first_name,'---'),ifnull(mm.last_name,'---') from movies as mv left join members as mm on mv.id=mm.movieid;
create view myview1 as select mv.title,ifnull(mm.first_name,'---'),ifnull(mm.last_name,'---') from movies as mv left join members as mm on mv.id=mm.movieid;
select * from myview1;
select * from authors;
select * from authors where authorid < 15;
create view aview as select * from authors where authorid < 15;
select * from aview;
insert into aview values (20,'john hamm');
select * from aview;
select * from authors;
drop view aview;
create view aview as select * from authors where authorid < 15 WITH CHECK option;
insert into aview values (22,'Sohn hamm');
insert into aview values (14,'Kohn hamm');
Select * from aview;
insert into aview values (11,'gohn hamm');
select * from authors;
